# Generated by Django 2.1.2 on 2018-11-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_context', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
