# Generated by Django 2.1.2 on 2018-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_context', '0004_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='writer',
            field=models.CharField(default='작성자', max_length=20),
        ),
    ]
